server:
  port: 8082

spring:
  application:
    name: auth-service
  cloud:
    consul:
      host: localhost
      port: 8500
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.springframework.web:
      servlet.DispatcherServlet: TRACE

security:
  jwt:
    token:
      header: Authorization
      secret-key: test
      expire-length: 604800