pipeline {
        agent any

        stages {
            stage('Project build') {
                steps {
                       echo 'building...'
//                     sh 'devops/build.sh'
                }
            }

            stage('Docker build') {
                steps {
                       echo 'docker building...'
//                     sh 'devops/docker-build.sh'
                }
            }

            stage('Docker push') {
                steps {
                       echo 'docker pushing...'
//                     sh 'devops/docker-push.sh'
                }
            }

            stage('Kubernetes deploy') {
                steps {
                       echo 'kubernetes deploy...'
//                     withCredentials([usernamePassword(credentialsId: 'fitness-club-push',
//                                                      usernameVariable: 'username',
//                                                      passwordVariable: 'password')]){
//
//                         sh 'devops/kubernetes-deploy.sh'
//                         sh "git push https://$username:$password@github.com/ShevelyanchikAlex/fitness-club-service.git --all"
//                     }
                }
            }
        }
    }