server:
  port: ${PORT:8084}

spring:
  application:
    name: news-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver

    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/news_service_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:user}
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: ERROR
    com.shevelyanchik: DEBUG
    root: INFO
