server:
  port: ${PORT:8084}

spring:
  application:
    name: news-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver

    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/news_service_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:user}
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

news-api:
  api-key: 0f0f49abdcc248bc905620645f0abd6d
  url: https://newsapi.org/v2/top-headlines?apiKey={apiKey}&category={category}&from={date}&country={country}

logging:
  level:
    org.springframework.web: ERROR
    com.shevelyanchik: DEBUG
    root: INFO
