--liquibase formatted sql

--changeset Aliaksandr_Shavialianchyk:create-service-table1.2

create table service
(
    id          bigint generated by default as identity primary key,
    description varchar(400)   not null,
    name        varchar(100)   not null,
    price       numeric(19, 2) not null
);