--liquibase formatted sql

--changeset Aliaksandr_Shavialianchyk:create-request-table1.2

create table request
(
    id                       bigint generated by default as identity primary key,
    created_date_time        timestamp   not null,
    request_status           varchar(30) not null,
    training_start_date_time timestamp   not null,
    service_id               bigint      not null,
    trainer_id               bigint      not null,
    user_id                  bigint      not null,
    foreign key (service_id)
        references service (id),
    foreign key (trainer_id)
        references trainer (id),
    foreign key (user_id)
        references users (id)
);