--liquibase formatted sql

--changeset Aliaksandr_Shavialianchyk:create-fitness-club-info-table1.2

create table fitness_club_info
(
    id          bigint generated by default as identity primary key,
    address     varchar(70)  not null,
    description varchar(400) not null
);