server:
  port: ${PORT:8765}
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://your.config.server.com"
  cloud:
    config:
      enabled: false
    consul:
      discovery:
        register: false
        registerHealthCheck: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: fitness-club-client
          uri: lb://fitness-club-client
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<path>.*), /$\{path}