server:
  port: ${PORT:8765}

spring:
  application:
    name: api-gateway

logging:
  level:
    org.springframework.web:
      HttpLogging: TRACE

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric