server:
  port: ${PORT:8765}

spring:
  application:
    name: api-gateway
  cloud:
    consul:
      config:
        enabled: false
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.web:
      HttpLogging: TRACE