apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-service
  namespace: default
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  selector:
    matchLabels:
      app: config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: shevelyanchik/config-service:113-a5e6e0f-kubernetes_task
          imagePullPolicy: Always
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: config-service-svc
  namespace: default
  labels:
    app: config-service
spec:
  selector:
    app: config-service
  ports:
    - protocol: "TCP"
      port: 8888
  type: LoadBalancer