apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  selector:
    matchLabels:
      app: email-service
  replicas: 1
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: shevelyanchik/email-service:113-a5e6e0f-kubernetes_task
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: KAFKA_BROKERS
              value: kafka-1680084936-0.kafka-1680084936-headless.default.svc.cluster.local:9092

---
apiVersion: v1
kind: Service
metadata:
  name: email-service-svc
spec:
  selector:
    app: email-service
  ports:
    - protocol: "TCP"
      port: 8083
  type: LoadBalancer