version: '3.8'

services:
  consul-service:
    image: bitnami/consul:1.15.0
    container_name: consul-service
    networks:
      - fitness-club-net
    ports:
      - '8500:8500'

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: zookeeper
    restart: always
    networks:
      - fitness-club-net
    expose:
      - "2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.3.1
    container_name: kafka
    restart: always
    networks:
      - fitness-club-net
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENERS: DOCKER://:29092,HOST://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: DOCKER://kafka:29092,HOST://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_DELETE_TOPIC_ENABLE: true
    volumes:
      - kafka-data:/bitnami/kafka

  kowl:
    image: quay.io/cloudhut/kowl:master-59f68da
    container_name: kowl
    restart: always
    networks:
      - fitness-club-net
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:29092
      SERVER_LISTENPORT: 9000

  redis:
    container_name: redis
    image: redis:6-alpine
    restart: always
    networks:
      - fitness-club-net
    ports:
      - "6379:6379"

  fitness-club-mongo:
    image: mongo:6.0.2
    command: mongod --auth
    container_name: fitness-club-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: user_db
    volumes:
      - fitness-club-mongo-data:/data/db
    networks:
      - fitness-club-net


volumes:
  zookeeper-data:
  kafka-data:
  fitness-club-mongo-data:

networks:
  fitness-club-net: