server:
  port: ${PORT:8080}

spring:
  application:
    name: user-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
  liquibase:
    enabled: true
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:user_db}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:root}
      authentication-database: ${MONGO_AUTH_DATABASE:admin}
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver

    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/user_service_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:user}
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: ERROR
    com.shevelyanchik: DEBUG
    root: INFO
