spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/fitness_club_db
    username: postgres
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: ERROR
    com.shevelyanchik: DEBUG
    root: INFO

security:
  jwt:
    token:
      header: Authorization
      secret-key: test
      expire-length: 604800