spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/fitness_club_db
    username: postgres
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

logging:
  #  file:
  #    name: logs/application-debug.log
  #  pattern:
  #    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: ERROR
    org.hibernate: INFO
    com.shevelyanchik.fitnessclub.web.aop.LoggingAspect: DEBUG

security:
  jwt:
    token:
      header: Authorization
      secret-key: test
      expire-length: 604800