#server:
#  port: 0
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: fitness-club-client
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/fitness_club_db
    username: postgres
    password: user
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true

logging:
  level:
    org.springframework.web: ERROR
    com.shevelyanchik: DEBUG
    root: INFO

security:
  jwt:
    token:
      header: Authorization
      secret-key: test
      expire-length: 604800