server:
  port: ${PORT:8082}

spring:
  application:
    name: auth-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.springframework.web:
      servlet.DispatcherServlet: TRACE

security:
  jwt:
    token:
      header: Authorization
      secret-key: test
      expire-length: 60480000