server:
  port: ${PORT:8888}

spring:
  application:
    name: config-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
    config:
      server:
        git:
          uri: https://github.com/ShevelyanchikAlex/fitness-club-service-config-dev